import { getStyleString, styles } from "../utils/templates";

export interface GenericEmailProps {
  bodyContent: string;
  senderName: string;
}

export function generateGenericEmailHTML({
  bodyContent,
  senderName,
}: GenericEmailProps): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Message from ${senderName}</title>
    </head>
    <body style="${getStyleString(styles.body)}">

        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td align="center" style="padding: 20px 0;">
                    <table border="0" cellpadding="0" cellspacing="0" width="600" style="${getStyleString(styles.container)}">
                        
                        <tr>
                            <td align="center" style="${getStyleString(styles.header)}">
                                <h1 style="color: #333333; margin: 0; font-size: 28px;">${senderName}</h1>
                            </td>
                        </tr>

                        <tr>
                            <td style="${getStyleString(styles.contentPadding)}">
                                
                                <p style="color: #555555; line-height: 1.6; margin-bottom: 20px;">
                                    ${bodyContent}
                                </p>
                                
                                <p style="color: #555555; line-height: 1.6; margin-bottom: 0;">
                                    This message was generated by your Financial Assistant.
                                </p>
                                <p style="color: #555555; line-height: 1.6; margin-bottom: 0;">
                                    Best regards,<br>The ${senderName} Team
                                </p>
                            </td>
                        </tr>

                        <tr>
                            <td align="center" style="padding: 20px 50px; border-top: 1px solid #eeeeee;">
                                <p style="color: #aaaaaa; font-size: 12px; margin: 0;">This is an automated email. Please do not reply.</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
    </html>
    `;
}